name: lens-mutable
version: 0.0.1

dependencies:
  - base
  - lens

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - lens-mutable
      - hspec
      - QuickCheck
